### ISSUE TITLE
Is the ESP8266 ESP-01 8 Mbit supported?

### ISSUE THREAD

**Issue by fkroepfl** [HofeBY/Tasmota-Firmware#2]
Do the FW builds also run on an ESP8266 ESP-01 8 Mbit?

Thank you in advance. 🤗

**Comment by HofeBY** [comment]
Try tasmota.bin like described in Liesmich-zuerst.txt in your home Language.
It contain´s SML and is tested against local TTL install ESP-01S 4096 KB, no OTA with to less Memory.

That´s why I prefer ESP32C6 Zero in SML Readhead. OTA is then easy.
https://de.aliexpress.com/item/1005006851575663.html?spm=a2g0o.order_list.order_list_main.5.4a345c5fnRPrd9&gatewayAdapt=glo2deu

**Comment by fkroepfl** [comment]
Thanks for the hint. 
The reason why I am interested in the ESP8266 ESP-01 is that there is a pluggable RS232 converter. And I need RS232 for my specific application.
